apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: sriov
spec:
  machineConfigSelector:
    matchExpressions:
    - {key: machineconfiguration.openshift.io/role, operator: In, values: [control-plane,master,sriov,worker]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/sriov: ""
  paused: false