apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: vm-fedora
  name: vm-fedora
  namespace: sriov-guests
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:   
        kubevirt.io/vm: vm-fedora
    spec:
      domain:
        cpu:
          cores: 6      
        resources:
          requests:
            memory: 16384M
        devices:
          disks:
          - name: containerdisk
            disk: {}
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          # - name: eth0
          #   masquerade: {}
          - name: nic01
            sriov: {}          
            macAddress: 1e:b3:5d:4e:ce:23
            model: e1000
      networks:
      # - name: eth0
      #   pod: {}
      - name: nic01
        multus:
          networkName: sriov-guests/mcx4-enp11s0f0np0-vlan10-dhcp
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/acmenezes/fedora-container-disk:latest
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora 
              chpasswd: { expire: False }
          name: cloudinitdisk      
          # cloudInitConfigDrive: 
          #   userData: |-
          #     #cloud-config
          #     user: alex
          #     password: fedora
          #     chpasswd: { expire: False }
      # accessCredentials:
      #   - sshPublicKey:
      #       propagationMethod:
      #         configDrive: {}
      #       source:
      #         secret:
      #           secretName: authorized-keys
                    