apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: vm-fedora-2
  name: vm-fedora-2
  namespace: sriov-guests
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:   
        kubevirt.io/vm: vm-fedora-2
        special: key
    spec:
      domain:
        cpu:
          cores: 6      
        resources:
          requests:
            memory: 16384M
        devices:
          disks:
          - name: containerdisk
            disk: {}
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: pod-network
            masquerade: {}
          - name: sriov-nic01
            macAddress: 40:a6:b7:26:a4:57          
            model: virtio
            sriov: {}
      networks:
      - name: pod-network
        pod: {}
      - name: sriov-nic01
        multus:
          networkName: sriov-guests/xxv710-ens3f0-vlan50-dhcp
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/acmenezes/fedora-container-disk:latest
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora 
              chpasswd: { expire: False }
          name: cloudinitdisk

                    